name: Docker Image CI

on: [push]

env:
  GIT_TAG: {{github.ref}}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: echo $GIT_TAG
#      run: docker build . --file Dockerfile --tag rtakaishi/vault-token-renewer:$(date +%s)
